#pragma once
#include <vector>
#define BUFFER std::vector<char>

#include "WSAInitializer.h"
#include <string>

enum MessageCodes
{
    MC_INITIAL_REQUEST = 101, //requests
    MC_INSERT_REQUEST = 102,
    MC_DELETE_REQUEST = 103,
    MC_REPLACE_REQUEST = 104,
    MC_CREATE_FILE_REQUEST = 105,
    MC_GET_FILES_REQUEST = 106,
    MC_CLOSE_FILE_REQUEST = 108,
    MC_GET_MESSAGES_REQUEST = 109,
    MC_GET_USERS_ON_FILE_REQUEST = 110,
    MC_POST_MSG_REQUEST = 111,
    MC_ENTER_FILE_REQUEST = 112,
    MC_EXIT_FILE_REQUEST = 113,
    MC_DELETE_FILE_REQUEST = 114,
    MC_GET_USERS_REQUEST = 115,
    MC_GET_USERS_PERMISSIONS_REQ_REQUEST = 116,
    MC_APPROVE_PERMISSION_REQUEST = 117,
    MC_REJECT_PERMISSION_REQUEST = 118,
    MC_PERMISSION_FILE_REQ_REQUEST = 119,
    MC_PROFILE_INFO_REQUEST = 120,
    MC_FRIENDS_LIST_REQUEST = 121,
    MC_PROJECTS_LIST_REQUEST = 122,
    MC_ADD_FRIEND_REQUEST = 123,
    MC_REMOVE_FRIEND_REQUEST = 124,
    MC_SEARCH_REQUEST = 125,
    MC_ENTER_PROJECT_REQUEST = 126,
    MC_EDIT_PROFILE_INFO_REQUEST = 127,
    MC_CREATE_PROJECT_REQUEST = 128,
    MC_MOVE_TO_CREATE_PROJ_WINDOW_REQUEST = 129,
    MC_GET_PROJECT_FILES_REQUEST = 130,
    MC_EXIT_PROJECT_REQUEST = 131,
    MC_DELETE_PROJECT_REQUEST = 132,
    MC_RENAME_FILE_REQUEST = 133,
    MC_GET_PROFILE_IMAGE_REQUEST = 134,
    MC_UPLOAD_PROFILE_IMAGE_REQUEST = 135,
    MC_APPROVE_FRIEND_REQ_REQUEST = 136,
    MC_REJECT_FRIEND_REQ_REQUEST = 137,
    MC_FRIEND_REQ_REQUEST = 138,
    MC_SEARCH_FRIENDS_REQUEST = 139,
    MC_BACK_TO_HOME_PAGE_REQUEST = 140,
    MC_USER_PROJECTS_LIST_REQUEST = 141,
    MC_LEAVE_PROJECT_REQUEST = 142,
    MC_ACCEPT_PROJECT_INVITE_REQUEST = 143,
    MC_DECLINE_PROJECT_INVITE_REQUEST = 144,
    MC_VIEW_PROJECT_INFO_REQUEST = 145,
    MC_EDIT_PROJECT_INFO_REQUEST = 146,
    MC_UPDATE_PROJECT_LIST_REQUEST = 147,
    MC_GET_PROJECT_INFO_REQUEST = 148,
    MC_MODIFY_PROJECT_INFO_REQUEST = 149,
    MC_GET_CODE_STYLES_REQUEST = 150,
    MC_SETTINGS_REQUEST = 151,

    MC_ERROR_RESP = 200, //responses
    MC_INITIAL_RESP = 201,
    MC_INSERT_RESP = 202,
    MC_DELETE_RESP = 203,
    MC_REPLACE_RESP = 204,
    MC_CREATE_FILE_RESP = 205,
    MC_GET_FILES_RESP = 206,
    MC_ADD_FILE_RESP = 207,
    MC_CLOSE_FILE_RESP = 208,
    MC_GET_MESSAGES_RESP = 209,
    MC_GET_USERS_ON_FILE_RESP = 210,
    MC_POST_MSG_RESP = 211,
    MC_ENTER_FILE_RESP = 212,
    MC_EXIT_FILE_RESP = 213,
    MC_DELETE_FILE_RESP = 214,
    MC_GET_USERS_RESP = 215,
    MC_GET_USERS_PERMISSIONS_REQ_RESP = 216,
    MC_APPROVE_PERMISSION_RESP = 217,
    MC_REJECT_PERMISSION_RESP = 218,
    MC_PERMISSION_FILE_REQ_RESP = 219,
    MC_PROFILE_INFO_RESP = 220,
    MC_FRIENDS_LIST_RESP = 221,
    MC_PROJECTS_LIST_RESP = 222,
    MC_ADD_FRIEND_RESP = 223,
    MC_REMOVE_FRIEND_RESP = 224,
    MC_SEARCH_RESP = 225,
    MC_ENTER_PROJECT_RESP = 226,
    MC_EDIT_PROFILE_INFO_RESP = 227,
    MC_CREATE_PROJECT_RESP = 228,
    MC_MOVE_TO_CREATE_PROJ_WINDOW_RESP = 229,
    MC_GET_PROJECT_FILES_RESP = 230,
    MC_EXIT_PROJECT_RESP = 231,
    MC_DELETE_PROJECT_RESP = 232,
    MC_RENAME_FILE_RESP = 233,
    MC_GET_PROFILE_IMAGE_RESP = 234,
    MC_UPLOAD_PROFILE_IMAGE_RESP = 235,
    MC_APPROVE_FRIEND_REQ_RESP = 236,
    MC_REJECT_FRIEND_REQ_RESP = 237,
    MC_FRIEND_REQ_RESP = 238,
    MC_SEARCH_FRIENDS_RESP = 239,
    MC_BACK_TO_HOME_PAGE_RESP = 240,
    MC_USER_PROJECTS_LIST_RESP = 241,
    MC_LEAVE_PROJECT_RESP = 242,
    MC_ACCEPT_PROJECT_INVITE_RESP = 243,
    MC_DECLINE_PROJECT_INVITE_RESP = 244,
    MC_VIEW_PROJECT_INFO_RESP = 245,
    MC_EDIT_PROJECT_INFO_RESP = 246,
    MC_UPDATE_PROJECT_LIST_RESP = 247,
    MC_GET_PROJECT_INFO_RESP = 248,
    MC_MODIFY_PROJECT_INFO_RESP = 249,
    MC_GET_CODE_STYLES_RESP = 250,
    MC_SETTINGS_RESP = 251,

    MC_DISCONNECT = 300, //user
    MC_LOGIN_REQUEST = 301,
    MC_LOGOUT_REQUEST = 306,
    MC_SIGNUP_REQUEST = 303,
    MC_FORGOT_PASSW_REQUEST = 304,

    MC_APPROVE_REQ_RESP = 302,
    MC_APPROVE_JOIN_RESP = 305,

    MC_LOGIN_RESP = 401,
    MC_SIGNUP_RESP = 403,
    MC_FORGOT_PASSW_RESP = 404,
    MC_LOGOUT_RESP = 406

};

class Helper
{
public:
    static void sendData(const SOCKET sc, const BUFFER message);

    static BUFFER getPartFromSocket(const SOCKET sc, const int bytesNum);
    static BUFFER getPartFromSocket(const SOCKET sc, const int bytesNum, const int flags);

    static bool IsConnectionError(const std::exception& e);
};
